on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: iterative/setup-dvc@v1
      - run: sudo apt install --yes fswatch
      - run: dvc exp run
